# Use an official Python runtime as base image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the contents into the container
COPY . .

# Install required packages
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Expose the port Railway expects
EXPOSE $PORT

# Command to run the app
CMD ["gunicorn", "backend.app:app", "--bind", "0.0.0.0:$PORT"]
